name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Display System Info
      run: |
        echo "Build #${{ github.run_number }}"
        echo "Running on branch: ${{ github.ref }}"
        date
        node --version
        npm --version
    
    - name: List Files
      run: ls -la
    
    - name: Run Tests
      run: npm test
